import { MotivationalPackage } from '@/types';

export const MOTIVATIONAL_PACKAGES_1_5: MotivationalPackage[] = [
  {
    id: 'pkg-1',
    title: 'First Steps',
    description: 'Encouragement for the beginning of your journey',
    icon: 'footprints',
    color: '#2EC4B6',
    unlockMilestoneDays: 0,
    statements: [
      'Every journey begins with a single step. You have already taken yours.',
      'You are braver than you believe, stronger than you seem.',
      'Today is your day one, not your day zero.',
      'The fact that you are here means you are ready for change.',
      'Recovery is not a race. Take it one moment at a time.',
      'You deserve a life free from the chains of addiction.',
      'Courage is not the absence of fear, it is acting in spite of it.',
      'Your past does not define your future.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=400',
  },
  {
    id: 'pkg-2',
    title: 'Inner Strength',
    description: 'Discover the power within you',
    icon: 'shield',
    color: '#FF6B35',
    unlockMilestoneDays: 1,
    statements: [
      'You have survived 100% of your worst days.',
      'Strength does not come from what you can do. It comes from overcoming what you once could not.',
      'You are not weak for struggling. You are strong for fighting.',
      'The strongest people are those who win battles we know nothing about.',
      'Your strength is greater than any craving.',
      'Every time you resist, you grow stronger.',
      'You are building a fortress of willpower, brick by brick.',
      'Believe in yourself. You have already proven you can do hard things.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=400',
  },
  {
    id: 'pkg-3',
    title: 'Healing Mind',
    description: 'Nurture your mental wellness',
    icon: 'brain',
    color: '#9B59B6',
    unlockMilestoneDays: 3,
    statements: [
      'Your mind is healing every single day you stay sober.',
      'Peace of mind is the ultimate luxury of recovery.',
      'Clarity comes when the fog of addiction lifts.',
      'Your thoughts are becoming your own again.',
      'Mental freedom is the greatest gift of sobriety.',
      'Every clear-headed morning is a victory.',
      'You are rewiring your brain for happiness.',
      'The mind, once stretched by a new experience, never returns to its old dimensions.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600',
      'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=400',
  },
  {
    id: 'pkg-4',
    title: 'Body Revival',
    description: 'Celebrate your physical healing',
    icon: 'heart-pulse',
    color: '#E74C3C',
    unlockMilestoneDays: 7,
    statements: [
      'Your body is thanking you with every sober day.',
      'Each cell in your body is regenerating and healing.',
      'You are giving your body the respect it deserves.',
      'Physical health is the foundation of a beautiful life.',
      'Your energy is returning. Feel the difference.',
      'Sleep is deeper, mornings are brighter.',
      'You are becoming the healthiest version of yourself.',
      'Honor your body — it is the only place you have to live.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600',
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
  },
  {
    id: 'pkg-5',
    title: 'Gratitude',
    description: 'Find thankfulness in each moment',
    icon: 'sparkles',
    color: '#F39C12',
    unlockMilestoneDays: 14,
    statements: [
      'Gratitude turns what we have into enough.',
      'Today I am grateful for the clarity to see beauty in small things.',
      'Thank you, past me, for choosing this path.',
      'Every sober moment is a gift I give myself.',
      'I am grateful for the people who believe in me.',
      'Gratitude is the healthiest of all human emotions.',
      'I find joy in the simple pleasures addiction once stole from me.',
      'Each new day is another chance to be thankful.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600',
      'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600',
      'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=400',
  },
];
