import { MotivationalPackage } from '@/types';

export const MOTIVATIONAL_PACKAGES_11_15: MotivationalPackage[] = [
  {
    id: 'pkg-11',
    title: 'Purpose',
    description: 'Discover your reason for being',
    icon: 'compass',
    color: '#795548',
    unlockMilestoneDays: 60,
    statements: [
      'Your life has a purpose that addiction tried to steal.',
      'You are here for a reason. Recovery reveals it.',
      'Purpose gives you the strength to resist temptation.',
      'When you know your why, you can endure any how.',
      'You are not just surviving - you are building a meaningful life.',
      'Every act of sobriety is an act of purpose.',
      'Your story will inspire someone else someday.',
      'Find what sets your soul on fire, and pursue it.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600',
      'https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400',
  },
  {
    id: 'pkg-12',
    title: 'Forgiveness',
    description: 'Release the weight of the past',
    icon: 'feather',
    color: '#009688',
    unlockMilestoneDays: 60,
    statements: [
      'Forgiveness is a gift you give yourself.',
      'Let go of guilt. You have paid enough.',
      'You cannot change yesterday, but you can forgive it.',
      'Holding onto anger is like drinking poison and expecting the other person to die.',
      'Forgive others not because they deserve it, but because you deserve peace.',
      'Self-forgiveness is the first step to true healing.',
      'Release the past. It has no power over your present.',
      'Every day is a fresh start to make amends.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
      'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=600',
      'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?w=400',
  },
  {
    id: 'pkg-13',
    title: 'Courage',
    description: 'Face your fears with bravery',
    icon: 'sword',
    color: '#FF5722',
    unlockMilestoneDays: 90,
    statements: [
      'Courage is not the absence of fear. It is the decision that something else is more important.',
      'You had the courage to start. You have the courage to continue.',
      'Fear is temporary. Regret is forever.',
      'Every time you face a trigger and choose sobriety, you are a warrior.',
      'Bravery is showing up when everything inside you says to hide.',
      'Your courage today creates your freedom tomorrow.',
      'Do the thing you fear, and the death of fear is certain.',
      'You are fiercer than any addiction.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400',
  },
  {
    id: 'pkg-14',
    title: 'Joy & Laughter',
    description: 'Rediscover genuine happiness',
    icon: 'smile',
    color: '#FFEB3B',
    unlockMilestoneDays: 90,
    statements: [
      'Real joy exists beyond the artificial highs.',
      'Laughter is returning, and it is genuine.',
      'You are rediscovering what it feels like to be truly happy.',
      'Joy is not found in a substance. It is found in a life well-lived.',
      'Celebrate the small moments of happiness today.',
      'Your smile is becoming real again.',
      'Happiness is a skill you are relearning every day.',
      'The best highs in life are natural ones.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1489710437720-ebb67ec84dd2?w=600',
      'https://images.unsplash.com/photo-1519834785169-98be25ec3f84?w=600',
      'https://images.unsplash.com/photo-1496275068113-fff8c90750d1?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1489710437720-ebb67ec84dd2?w=400',
  },
  {
    id: 'pkg-15',
    title: 'Patience',
    description: 'Trust the process of recovery',
    icon: 'hourglass',
    color: '#4CAF50',
    unlockMilestoneDays: 90,
    statements: [
      'Recovery is a marathon, not a sprint.',
      'Good things take time. Be patient with yourself.',
      'Rome was not built in a day, and neither is recovery.',
      'Trust the process, even when you cannot see the progress.',
      'Patience is not about waiting. It is about keeping a good attitude while working hard.',
      'Slow progress is still progress.',
      'The seeds you plant today will bloom in time.',
      'Have patience. All things are difficult before they become easy.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=600',
      'https://images.unsplash.com/photo-1444930694458-01babf71870c?w=600',
      'https://images.unsplash.com/photo-1486728297118-82a07bc48a28?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=400',
  },
];
