import { MotivationalPackage } from '@/types';

export const MOTIVATIONAL_PACKAGES_21_25: MotivationalPackage[] = [
  {
    id: 'pkg-21',
    title: 'Service',
    description: 'Help others on their journey',
    icon: 'hand-helping',
    color: '#FF7043',
    unlockMilestoneDays: 365,
    statements: [
      'The best way to stay sober is to help someone else get sober.',
      'Your experience can light the way for someone in darkness.',
      'Service to others is the rent you pay for your room here on earth.',
      'When you help others, you help yourself.',
      'Be the person you needed when you were struggling.',
      'Your recovery gives you the power to uplift others.',
      'One recovering person can change the world.',
      'In giving, we receive.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600',
      'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600',
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=400',
  },
  {
    id: 'pkg-22',
    title: 'Abundance',
    description: 'Embrace the fullness of sober life',
    icon: 'sun',
    color: '#FFA726',
    unlockMilestoneDays: 730,
    statements: [
      'Sobriety opens doors you never knew existed.',
      'Abundance flows when addiction no longer blocks it.',
      'You have more time, more energy, more love to give.',
      'The life you are building is richer than anything addiction promised.',
      'True abundance is waking up clear-headed and grateful.',
      'You are saving money, time, and most importantly - yourself.',
      'An abundant life awaits those who choose recovery.',
      'Count your blessings, not your cravings.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=600',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=400',
  },
  {
    id: 'pkg-23',
    title: 'Peace',
    description: 'Find serenity in sobriety',
    icon: 'leaf',
    color: '#66BB6A',
    unlockMilestoneDays: 730,
    statements: [
      'Peace is the reward of a disciplined mind.',
      'In sobriety, you find a peace that surpasses all understanding.',
      'Calm is a superpower. Sobriety gives it to you.',
      'Inner peace begins the moment you choose not to let your addiction control you.',
      'Serenity is not the absence of conflict, but the ability to cope with it.',
      'You have earned this peace. Protect it.',
      'A peaceful mind is a powerful mind.',
      'Let go of chaos. Embrace the calm.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
      'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=600',
      'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=400',
  },
  {
    id: 'pkg-24',
    title: 'Mastery',
    description: 'You have mastered the art of recovery',
    icon: 'award',
    color: '#5C6BC0',
    unlockMilestoneDays: 1095,
    statements: [
      'You have mastered what many never attempt.',
      'Three years is not just time - it is a testament to your character.',
      'Mastery is not perfection. It is consistent, dedicated practice.',
      'You are living proof that recovery works.',
      'Your discipline has become your freedom.',
      'What once seemed impossible is now your everyday reality.',
      'You have not just recovered. You have transcended.',
      'The master has failed more times than the beginner has tried.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600',
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=600',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=400',
  },
  {
    id: 'pkg-25',
    title: 'Transformation',
    description: 'Celebrate your complete rebirth',
    icon: 'star',
    color: '#AB47BC',
    unlockMilestoneDays: 1825,
    statements: [
      'Five years. You are not the same person. You are transformed.',
      'Your transformation is nothing short of miraculous.',
      'You have risen from the ashes like a phoenix.',
      'The caterpillar does not know it will become a butterfly. But you did - and you became one.',
      'Your life is a masterpiece painted with the colors of perseverance.',
      'Transformation is the ultimate proof of the human spirit.',
      'You have done what many thought impossible. Be proud.',
      'Your journey from darkness to light inspires the world.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400',
  },
];
