import { MotivationalPackage } from '@/types';

export const MOTIVATIONAL_PACKAGES_6_10: MotivationalPackage[] = [
  {
    id: 'pkg-6',
    title: 'Self-Compassion',
    description: 'Learn to be kind to yourself',
    icon: 'hand-heart',
    color: '#E91E63',
    unlockMilestoneDays: 14,
    statements: [
      'You are worthy of love, especially from yourself.',
      'Be gentle with yourself. You are doing the best you can.',
      'Forgive yourself. You were doing the best you knew how.',
      'Self-compassion is not weakness - it is wisdom.',
      'You deserve the same kindness you give to others.',
      'It is okay to not be okay. What matters is that you keep going.',
      'Treat yourself like someone you are responsible for helping.',
      'Your imperfections make you human, not unworthy.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600',
      'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=600',
      'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400',
  },
  {
    id: 'pkg-7',
    title: 'Resilience',
    description: 'Bounce back stronger than before',
    icon: 'refresh-cw',
    color: '#00BCD4',
    unlockMilestoneDays: 30,
    statements: [
      'Resilience is knowing that you are the only one who can save yourself.',
      'Fall seven times, stand up eight.',
      'You are not what happened to you. You are what you choose to become.',
      'A setback is a setup for a comeback.',
      'Tough times do not last. Tough people do.',
      'Every challenge you face is making you more resilient.',
      'You have been through worse and survived. You will survive this too.',
      'Resilience is your superpower.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600',
      'https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=400',
  },
  {
    id: 'pkg-8',
    title: 'New Identity',
    description: 'Embrace who you are becoming',
    icon: 'user-check',
    color: '#8BC34A',
    unlockMilestoneDays: 30,
    statements: [
      'You are not your addiction. You are so much more.',
      'Every day you write a new chapter of your story.',
      'The person you are becoming will cost you friendships, relationships, and comfort zones - and it is worth it.',
      'You are shedding an old skin and growing a new one.',
      'Identity is not fixed. You are evolving.',
      'Choose who you want to be, then prove it with your actions.',
      'You are becoming someone your future self will thank.',
      'The best project you will ever work on is you.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1492681290082-e932832941e6?w=600',
      'https://images.unsplash.com/photo-1517960413843-0aee8e2b3285?w=600',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1492681290082-e932832941e6?w=400',
  },
  {
    id: 'pkg-9',
    title: 'Mindfulness',
    description: 'Stay present in the moment',
    icon: 'eye',
    color: '#607D8B',
    unlockMilestoneDays: 30,
    statements: [
      'This moment is all you have. Make it count.',
      'Breathe in peace, breathe out tension.',
      'You cannot change the past, but you can shape this moment.',
      'Mindfulness means being where you are, not where you were.',
      'Observe your cravings without judgment. They will pass.',
      'The present moment is a place of power.',
      'Stillness is where creativity and solutions are found.',
      'When you own your breath, nobody can steal your peace.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=600',
      'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?w=600',
      'https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=400',
  },
  {
    id: 'pkg-10',
    title: 'Relationships',
    description: 'Rebuild connections that matter',
    icon: 'users',
    color: '#3F51B5',
    unlockMilestoneDays: 60,
    statements: [
      'Recovery opens the door to authentic relationships.',
      'The people who love you are cheering you on.',
      'You are becoming someone others can truly rely on.',
      'Vulnerability is the birthplace of connection.',
      'Healthy relationships flourish in sobriety.',
      'You deserve people who celebrate your progress.',
      'Trust is rebuilt one honest day at a time.',
      'Connection is the opposite of addiction.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600',
      'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=600',
      'https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
  },
];
