import { MotivationalPackage } from '../../types';

export const MOTIVATIONAL_PACKAGES_16_20: MotivationalPackage[] = [
  {
    id: 'pkg-16',
    title: 'Freedom',
    description: 'Embrace your liberation',
    icon: 'bird',
    color: '#03A9F4',
    unlockMilestoneDays: 180,
    statements: [
      'Freedom tastes better than any substance ever could.',
      'You are no longer a prisoner of your cravings.',
      'Sobriety is not giving something up. It is gaining everything.',
      'You are free to choose who you want to be.',
      'Liberation from addiction is the ultimate freedom.',
      'Every chain you break makes you lighter.',
      'You are living proof that freedom is possible.',
      'The cage door is open. Keep flying.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1470115636492-6d2b56f9b87d?w=600',
      'https://images.unsplash.com/photo-1504198266287-1659872e6590?w=600',
      'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1470115636492-6d2b56f9b87d?w=400',
  },
  {
    id: 'pkg-17',
    title: 'Wisdom',
    description: 'Learn from your experiences',
    icon: 'book-open',
    color: '#673AB7',
    unlockMilestoneDays: 180,
    statements: [
      'Wisdom is born from the ashes of our struggles.',
      'Your experience is your greatest teacher.',
      'The lessons of addiction are painful, but they are powerful.',
      'You know things now that you did not know before. Use them.',
      'Wisdom is knowing that every day sober is a day well spent.',
      'Your struggles have given you a perspective others may never have.',
      'Knowledge is learning from your own mistakes. Wisdom is learning from them and helping others.',
      'You carry wisdom that textbooks cannot teach.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400',
  },
  {
    id: 'pkg-18',
    title: 'Self-Worth',
    description: 'Recognize your true value',
    icon: 'gem',
    color: '#E040FB',
    unlockMilestoneDays: 180,
    statements: [
      'You are worth more than your worst moments.',
      'Your value does not decrease based on someone else\'s inability to see your worth.',
      'You are a diamond in the rough - recovery is the polishing.',
      'You deserve good things. Believe that.',
      'Self-worth comes from within. No substance can provide it.',
      'You are enough. You have always been enough.',
      'Treat yourself with the dignity you deserve.',
      'Your worth is not measured by your past but by your present choices.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?w=600',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1468276311594-df7cb65d8df6?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1496449903678-68ddcb189a24?w=400',
  },
  {
    id: 'pkg-19',
    title: 'Growth Mindset',
    description: 'Embrace continuous improvement',
    icon: 'trending-up',
    color: '#4DB6AC',
    unlockMilestoneDays: 365,
    statements: [
      'Growth is uncomfortable, but so is staying the same.',
      'You are not who you were yesterday. You are evolving.',
      'Every day is an opportunity to become a better version of yourself.',
      'Mistakes are proof that you are trying.',
      'A growth mindset turns obstacles into opportunities.',
      'You have not come this far to only come this far.',
      'The only limit to your growth is the limit you place on yourself.',
      'Progress, not perfection, is the goal.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600',
      'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=600',
      'https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?w=400',
  },
  {
    id: 'pkg-20',
    title: 'Legacy',
    description: 'Build a life worth remembering',
    icon: 'crown',
    color: '#FFD700',
    unlockMilestoneDays: 365,
    statements: [
      'You are building a legacy that your family will be proud of.',
      'The life you are creating in recovery is your masterpiece.',
      'What you do today echoes in eternity.',
      'Your recovery story will change lives.',
      'You are not just saving yourself - you are saving your future.',
      'Leave footprints of love, not tracks of destruction.',
      'A year from now you will be glad you started today.',
      'The greatest legacy is a life lived in integrity.',
    ],
    imageUrls: [
      'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=600',
      'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=600',
      'https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600',
    ],
    thumbnailUrl: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=400',
  },
];
