import { WorkbookSection } from '@/types';

export const WORKBOOK_SECTIONS_6_10: WorkbookSection[] = [
  {
    id: 'sec-6',
    title: 'Self-Esteem & Identity',
    description: 'Rebuild your sense of self-worth',
    unlockMilestoneDays: 7,
    questions: [
      { id: 's6q1', type: 'reflection', question: 'How has addiction affected your self-esteem? Be specific.' },
      { id: 's6q2', type: 'assignment', question: 'Write down 10 positive qualities about yourself. If you struggle, ask someone who cares about you.', hint: 'This may be difficult but push through.' },
      { id: 's6q3', type: 'journaling', question: 'Who were you before addiction? Describe the person you remember.' },
      { id: 's6q4', type: 'reflection', question: 'What negative beliefs about yourself does your addiction reinforce?' },
      { id: 's6q5', type: 'exercise', question: 'Each morning for a week, look in the mirror and say one kind thing to yourself. Write about how this practice evolves.' },
      { id: 's6q6', type: 'reflection', question: 'How do you define yourself outside of your addiction? What roles do you play?' },
      { id: 's6q7', type: 'assignment', question: 'Write 5 affirmations about yourself that counter your negative self-talk. Practice saying them daily.' },
      { id: 's6q8', type: 'journaling', question: 'Describe a time when someone made you feel valuable. What did they say or do?' },
      { id: 's6q9', type: 'reflection', question: 'How does comparison to others affect your self-esteem? How can you combat this?' },
      { id: 's6q10', type: 'reflection', question: 'What achievements are you most proud of, even small ones?' },
      { id: 's6q11', type: 'journaling', question: 'Write about the person you want to become. What qualities will they have?' },
      { id: 's6q12', type: 'reflection', question: 'How does shame differ from guilt? Which one do you experience more?' },
      { id: 's6q13', type: 'assignment', question: 'Identify 3 activities that make you feel competent and confident. Schedule them this week.' },
      { id: 's6q14', type: 'reflection', question: 'What would you attempt if you knew you could not fail?' },
      { id: 's6q15', type: 'exercise', question: 'Write yourself a permission slip: "I give myself permission to..." Complete with 5 things.' },
      { id: 's6q16', type: 'journaling', question: 'How has your identity shifted since beginning recovery? What surprises you?' },
      { id: 's6q17', type: 'reflection', question: 'What labels have you been given that no longer serve you? How can you shed them?' },
      { id: 's6q18', type: 'assignment', question: 'Ask 3 people you trust to describe you in 3 words. Write their responses and your reaction.' },
      { id: 's6q19', type: 'reflection', question: 'How does your self-talk change on good days versus bad days?' },
      { id: 's6q20', type: 'journaling', question: 'Write a compassionate letter to yourself as if you were writing to your best friend going through recovery.' },
    ],
  },
  {
    id: 'sec-7',
    title: 'Family & Relationships',
    description: 'Heal and strengthen your connections',
    unlockMilestoneDays: 7,
    questions: [
      { id: 's7q1', type: 'reflection', question: 'How has your addiction affected your closest relationships?' },
      { id: 's7q2', type: 'journaling', question: 'Write about the person your addiction has hurt the most. What would you say to them?' },
      { id: 's7q3', type: 'assignment', question: 'List the relationships you want to repair. For each, write one small step you can take this week.' },
      { id: 's7q4', type: 'reflection', question: 'What patterns from your family of origin contribute to your addiction?' },
      { id: 's7q5', type: 'journaling', question: 'Describe what a healthy relationship looks like to you.' },
      { id: 's7q6', type: 'reflection', question: 'Which relationships in your life are enabling your addiction? How can you set boundaries?' },
      { id: 's7q7', type: 'assignment', question: 'Write a list of boundaries you need to set with specific people. Practice saying them out loud.' },
      { id: 's7q8', type: 'reflection', question: 'How do you handle conflict in relationships? Is it healthy?' },
      { id: 's7q9', type: 'exercise', question: 'Practice active listening with someone today: Listen without planning your response. Write about the experience.' },
      { id: 's7q10', type: 'reflection', question: 'What do you need from your support system right now?' },
      { id: 's7q11', type: 'journaling', question: 'Write about trust. How has it been broken? How can it be rebuilt?' },
      { id: 's7q12', type: 'reflection', question: 'How has codependency played a role in your relationships and addiction?' },
      { id: 's7q13', type: 'assignment', question: 'Reach out to one person this week to strengthen your connection. Write about how it went.' },
      { id: 's7q14', type: 'reflection', question: 'What does forgiveness look like in the context of damaged relationships?' },
      { id: 's7q15', type: 'journaling', question: 'Describe the relationship you have with yourself. Is it kind? Critical? Nurturing?' },
      { id: 's7q16', type: 'reflection', question: 'How do you express love and appreciation to the people in your life?' },
      { id: 's7q17', type: 'exercise', question: 'Write an apology letter to someone you have hurt (you do not have to send it). How does writing it make you feel?' },
      { id: 's7q18', type: 'reflection', question: 'What role does loneliness play in your addiction? How can you address it?' },
      { id: 's7q19', type: 'assignment', question: 'Identify 3 toxic relationship patterns you want to change. Write a healthier alternative for each.' },
      { id: 's7q20', type: 'journaling', question: 'What kind of friend, partner, or family member do you want to be in recovery?' },
    ],
  },
  {
    id: 'sec-8',
    title: 'Stress Management',
    description: 'Develop healthy ways to handle stress',
    unlockMilestoneDays: 14,
    questions: [
      { id: 's8q1', type: 'reflection', question: 'What are your top 5 sources of stress right now?' },
      { id: 's8q2', type: 'assignment', question: 'Rate each stressor on a scale of 1-10. Which ones can you control? Which ones can you not?' },
      { id: 's8q3', type: 'journaling', question: 'Write about how stress and your addiction are connected.' },
      { id: 's8q4', type: 'exercise', question: 'Practice the "4-7-8" breathing technique for 5 minutes. Write about the effect on your stress level.' },
      { id: 's8q5', type: 'reflection', question: 'What physical symptoms do you experience when stressed?' },
      { id: 's8q6', type: 'assignment', question: 'Create a "stress first aid kit" - list 10 things that help you decompress.', hint: 'Bath, walk, music, tea, calling a friend, etc.' },
      { id: 's8q7', type: 'reflection', question: 'How do you typically respond to stress? Fight, flight, freeze, or fawn?' },
      { id: 's8q8', type: 'journaling', question: 'Write about a time you handled stress well without turning to your addiction.' },
      { id: 's8q9', type: 'reflection', question: 'What role does perfectionism play in your stress levels?' },
      { id: 's8q10', type: 'exercise', question: 'Try a body scan meditation: Slowly focus on each part of your body from head to toe. Write about tension you discovered.' },
      { id: 's8q11', type: 'reflection', question: 'How can saying "no" reduce your stress? What do you need to say no to?' },
      { id: 's8q12', type: 'assignment', question: 'Plan a "stress-free" day this week. What would it include? Execute the plan and write about it.' },
      { id: 's8q13', type: 'reflection', question: 'How does your work or financial situation contribute to stress? What small changes can you make?' },
      { id: 's8q14', type: 'journaling', question: 'Write about the connection between your stress and sleep patterns.' },
      { id: 's8q15', type: 'reflection', question: 'What activities bring you peace? How often do you do them?' },
      { id: 's8q16', type: 'exercise', question: 'Spend 20 minutes in nature today without your phone. Write about how you feel afterward.' },
      { id: 's8q17', type: 'reflection', question: 'How does exercise affect your stress levels? What type of exercise works best for you?' },
      { id: 's8q18', type: 'assignment', question: 'Write a daily schedule that builds in stress-relief breaks throughout the day.' },
      { id: 's8q19', type: 'reflection', question: 'What thought patterns increase your stress? How can you challenge them?' },
      { id: 's8q20', type: 'journaling', question: 'If stress had a shape, color, and sound, what would it be? Describe it creatively.' },
    ],
  },
  {
    id: 'sec-9',
    title: 'Mindfulness & Meditation',
    description: 'Cultivate present-moment awareness',
    unlockMilestoneDays: 14,
    questions: [
      { id: 's9q1', type: 'reflection', question: 'What does mindfulness mean to you? Have you practiced it before?' },
      { id: 's9q2', type: 'exercise', question: 'Sit in silence for 5 minutes focusing only on your breath. Write about what came up.' },
      { id: 's9q3', type: 'journaling', question: 'Describe a moment today when you were fully present. What made it special?' },
      { id: 's9q4', type: 'reflection', question: 'How much time do you spend worrying about the future or regretting the past?' },
      { id: 's9q5', type: 'exercise', question: 'Do a mindful walk: Walk slowly for 10 minutes, noticing every sensation. Write your observations.' },
      { id: 's9q6', type: 'reflection', question: 'How can mindfulness help you manage cravings?' },
      { id: 's9q7', type: 'assignment', question: 'Commit to 5 minutes of meditation daily this week. Track your practice and write about your experience each day.' },
      { id: 's9q8', type: 'reflection', question: 'What thoughts repeatedly distract you during quiet moments?' },
      { id: 's9q9', type: 'exercise', question: 'Practice mindful eating with one meal today. Notice colors, textures, flavors, and sensations. Write about it.' },
      { id: 's9q10', type: 'journaling', question: 'Write about a time when being present changed your perspective on a situation.' },
      { id: 's9q11', type: 'reflection', question: 'What obstacles prevent you from being mindful? How can you overcome them?' },
      { id: 's9q12', type: 'exercise', question: 'Practice the "STOP" technique: Stop, Take a breath, Observe, Proceed. Use it 3 times today and write about it.' },
      { id: 's9q13', type: 'reflection', question: 'How does your phone and technology use affect your ability to be present?' },
      { id: 's9q14', type: 'assignment', question: 'Create a mindfulness reminder system (alarms, sticky notes, etc.) and use it for a week. Report your findings.' },
      { id: 's9q15', type: 'reflection', question: 'How does mindfulness differ from emptying your mind?' },
      { id: 's9q16', type: 'journaling', question: 'Write about your inner critic. What does it say? How can mindfulness help you respond to it?' },
      { id: 's9q17', type: 'exercise', question: 'Do a loving-kindness meditation: Send good wishes to yourself, a loved one, a neutral person, and a difficult person. Write about the experience.' },
      { id: 's9q18', type: 'reflection', question: 'How has mindfulness or meditation affected your recovery so far?' },
      { id: 's9q19', type: 'assignment', question: 'Identify 3 daily activities you can turn into mindfulness practices (brushing teeth, showering, commuting).' },
      { id: 's9q20', type: 'journaling', question: 'Write about the concept of "non-judgment." How can you apply it to yourself and your recovery?' },
    ],
  },
  {
    id: 'sec-10',
    title: 'Anger & Resentment',
    description: 'Process and release toxic anger',
    unlockMilestoneDays: 30,
    questions: [
      { id: 's10q1', type: 'reflection', question: 'What makes you angry most often? List your top triggers.' },
      { id: 's10q2', type: 'journaling', question: 'Write about a resentment you have been carrying. How long have you held onto it?' },
      { id: 's10q3', type: 'reflection', question: 'How does unresolved anger contribute to your addiction?' },
      { id: 's10q4', type: 'assignment', question: 'Create a resentment inventory: List people you resent, why, and how it affects you.' },
      { id: 's10q5', type: 'exercise', question: 'When you feel angry today, pause and take 10 deep breaths before responding. Write about what happened.' },
      { id: 's10q6', type: 'reflection', question: 'Is your anger usually directed outward or inward? How does each manifest?' },
      { id: 's10q7', type: 'journaling', question: 'Write a letter to someone you are angry at (do not send it). Express everything you need to say.' },
      { id: 's10q8', type: 'reflection', question: 'What role does suppressed anger play in your life? What happens when you suppress it?' },
      { id: 's10q9', type: 'assignment', question: 'List 5 healthy ways to express anger and practice one this week.' },
      { id: 's10q10', type: 'reflection', question: 'How does holding resentment keep you stuck in the past?' },
      { id: 's10q11', type: 'exercise', question: 'Try physical release: Go for a run, punch a pillow, or do intense exercise when angry. Write about the experience.' },
      { id: 's10q12', type: 'reflection', question: 'What is the difference between righteous anger and toxic anger?' },
      { id: 's10q13', type: 'journaling', question: 'Write about a time someone hurt you deeply. Can you see their perspective? Can you find compassion?' },
      { id: 's10q14', type: 'reflection', question: 'How does unforgiveness hurt you more than the person you are angry at?' },
      { id: 's10q15', type: 'assignment', question: 'Choose one resentment and take one step toward releasing it. Write about the process.' },
      { id: 's10q16', type: 'reflection', question: 'What role does pride play in your anger and resentments?' },
      { id: 's10q17', type: 'journaling', question: 'Write about what it would feel like to truly let go of all your resentments.' },
      { id: 's10q18', type: 'reflection', question: 'How has anger protected you in the past? Is that protection still needed?' },
      { id: 's10q19', type: 'exercise', question: 'Practice the phrase "I choose peace over this" when anger arises. Use it for one full day and report.' },
      { id: 's10q20', type: 'journaling', question: 'Imagine your anger as weather. Describe it. Now imagine it passing. What remains?' },
    ],
  },
];
