import { WorkbookSection } from '@/types';

export const WORKBOOK_SECTIONS_11_15: WorkbookSection[] = [
  {
    id: 'sec-11',
    title: 'Grief & Loss',
    description: 'Mourn what addiction has taken from you',
    unlockMilestoneDays: 30,
    questions: [
      { id: 's11q1', type: 'reflection', question: 'What have you lost because of your addiction? Be thorough.' },
      { id: 's11q2', type: 'journaling', question: 'Write about the life you imagined for yourself before addiction took hold.' },
      { id: 's11q3', type: 'reflection', question: 'Are you grieving the loss of your addiction itself? This is normal. Describe the feeling.' },
      { id: 's11q4', type: 'assignment', question: 'Write a eulogy for your addiction. What are you saying goodbye to?' },
      { id: 's11q5', type: 'reflection', question: 'What stage of grief are you in right now? (Denial, Anger, Bargaining, Depression, Acceptance)' },
      { id: 's11q6', type: 'journaling', question: 'Write about a relationship lost to addiction. What do you miss most?' },
      { id: 's11q7', type: 'reflection', question: 'How do you typically handle loss? Do you face it or avoid it?' },
      { id: 's11q8', type: 'exercise', question: 'Allow yourself 15 minutes to fully feel your grief without distraction. Write about what emerged.' },
      { id: 's11q9', type: 'reflection', question: 'What opportunities has addiction stolen from you?' },
      { id: 's11q10', type: 'assignment', question: 'Create a "loss timeline" marking significant losses related to your addiction.' },
      { id: 's11q11', type: 'journaling', question: 'Write about the version of yourself that you lost to addiction. Who were they?' },
      { id: 's11q12', type: 'reflection', question: 'How can you honor what you have lost while still moving forward?' },
      { id: 's11q13', type: 'exercise', question: 'Create a small ritual of letting go: Write a loss on paper and safely burn or tear it up. Describe the experience.' },
      { id: 's11q14', type: 'reflection', question: 'What new things has recovery brought into your life to replace what was lost?' },
      { id: 's11q15', type: 'journaling', question: 'Write a letter to your past self before addiction. What would you say?' },
      { id: 's11q16', type: 'reflection', question: 'How does unprocessed grief manifest in your daily life?' },
      { id: 's11q17', type: 'assignment', question: 'Identify 3 healthy ways to process grief and commit to practicing one this week.' },
      { id: 's11q18', type: 'reflection', question: 'Can you find any meaning or growth in your losses?' },
      { id: 's11q19', type: 'journaling', question: 'Write about acceptance. What does it mean to accept your losses without condoning what happened?' },
      { id: 's11q20', type: 'reflection', question: 'What would it take for you to feel at peace with your past?' },
    ],
  },
  {
    id: 'sec-12',
    title: 'Healthy Habits',
    description: 'Build a foundation of positive daily routines',
    unlockMilestoneDays: 30,
    questions: [
      { id: 's12q1', type: 'reflection', question: 'What does your current morning routine look like? How does it serve your recovery?' },
      { id: 's12q2', type: 'assignment', question: 'Design your ideal morning routine that supports recovery. Include at least 5 elements.' },
      { id: 's12q3', type: 'journaling', question: 'Write about a healthy habit you have successfully built. What made it stick?' },
      { id: 's12q4', type: 'reflection', question: 'How many hours of sleep do you get? How does sleep affect your recovery?' },
      { id: 's12q5', type: 'exercise', question: 'Track everything you eat for one day. Are you nourishing your body? Write your observations.' },
      { id: 's12q6', type: 'reflection', question: 'What role does hydration play in how you feel physically and mentally?' },
      { id: 's12q7', type: 'assignment', question: 'Create a weekly exercise plan that you can realistically follow. Include variety.' },
      { id: 's12q8', type: 'reflection', question: 'How does clutter in your environment affect your mental state?' },
      { id: 's12q9', type: 'exercise', question: 'Clean and organize one space in your home. Write about how the space and you feel afterward.' },
      { id: 's12q10', type: 'journaling', question: 'Describe your ideal evening routine. How does it help you wind down and prepare for sleep?' },
      { id: 's12q11', type: 'reflection', question: 'What bad habits have replaced your addiction? Are they harmful?' },
      { id: 's12q12', type: 'assignment', question: 'Choose one new healthy habit to start this week. Track it daily and write about your progress.' },
      { id: 's12q13', type: 'reflection', question: 'How does regular movement and exercise change your mood and cravings?' },
      { id: 's12q14', type: 'journaling', question: 'Write about the connection between nutrition and your mental health.' },
      { id: 's12q15', type: 'reflection', question: 'What role does routine play in your recovery? Does structure help or stress you?' },
      { id: 's12q16', type: 'exercise', question: 'Go to bed 30 minutes earlier than usual tonight. Write about how you feel the next morning.' },
      { id: 's12q17', type: 'reflection', question: 'How much screen time do you have daily? Is it helping or hindering your recovery?' },
      { id: 's12q18', type: 'assignment', question: 'Create a self-care checklist with 10 items. Practice checking off at least 5 daily.' },
      { id: 's12q19', type: 'reflection', question: 'What is one habit you know you should start but keep putting off? What is holding you back?' },
      { id: 's12q20', type: 'journaling', question: 'Write about how your daily habits will look 6 months from now if you stay on this path.' },
    ],
  },
  {
    id: 'sec-13',
    title: 'Financial Recovery',
    description: 'Rebuild your financial health and relationship with money',
    unlockMilestoneDays: 60,
    questions: [
      { id: 's13q1', type: 'reflection', question: 'How much money has your addiction cost you overall? Include direct and indirect costs.' },
      { id: 's13q2', type: 'assignment', question: 'Create a simple monthly budget. Include income, expenses, savings, and debt payments.' },
      { id: 's13q3', type: 'journaling', question: 'Write about your relationship with money. Is it healthy?' },
      { id: 's13q4', type: 'reflection', question: 'What financial damage from addiction still needs to be addressed?' },
      { id: 's13q5', type: 'assignment', question: 'List all debts related to your addiction. Create a basic plan to address each one.' },
      { id: 's13q6', type: 'reflection', question: 'How does financial stress trigger your addiction?' },
      { id: 's13q7', type: 'exercise', question: 'Track every dollar you spend for 3 days. Write about patterns you notice.' },
      { id: 's13q8', type: 'journaling', question: 'What financial goals do you have for the next year? How does sobriety support them?' },
      { id: 's13q9', type: 'reflection', question: 'How can saving money be a source of motivation in recovery?' },
      { id: 's13q10', type: 'assignment', question: 'Calculate how much money you save daily/weekly/monthly/yearly by being sober.' },
      { id: 's13q11', type: 'reflection', question: 'What would you do with the money you save through sobriety?' },
      { id: 's13q12', type: 'journaling', question: 'Write about financial amends you need to make and how you plan to address them.' },
      { id: 's13q13', type: 'reflection', question: 'How does financial stability contribute to your overall well-being and recovery?' },
      { id: 's13q14', type: 'assignment', question: 'Open a savings account (or designate one) specifically for money saved through sobriety.' },
      { id: 's13q15', type: 'reflection', question: 'What financial habits from your addiction do you need to change?' },
      { id: 's13q16', type: 'exercise', question: 'Set up automatic savings of your daily savings amount. Write about how taking this step feels.' },
      { id: 's13q17', type: 'reflection', question: 'How does impulsive spending relate to addictive behavior? Are you impulsive with money?' },
      { id: 's13q18', type: 'journaling', question: 'Write about what financial freedom means to you and how recovery brings you closer to it.' },
      { id: 's13q19', type: 'reflection', question: 'What financial lessons has your addiction taught you?' },
      { id: 's13q20', type: 'assignment', question: 'Create a reward plan: For every financial milestone you reach in recovery, plan a healthy celebration.' },
    ],
  },
  {
    id: 'sec-14',
    title: 'Boundaries',
    description: 'Learn to set and maintain healthy boundaries',
    unlockMilestoneDays: 60,
    questions: [
      { id: 's14q1', type: 'reflection', question: 'What does having healthy boundaries mean to you?' },
      { id: 's14q2', type: 'assignment', question: 'List 5 boundaries you need to set in your life right now. Be specific about with whom and about what.' },
      { id: 's14q3', type: 'journaling', question: 'Write about a time when a lack of boundaries led to a relapse or close call.' },
      { id: 's14q4', type: 'reflection', question: 'Why is it difficult for you to say no? What are you afraid of?' },
      { id: 's14q5', type: 'exercise', question: 'Practice saying "no" to one request this week. Write about the experience and how it felt.' },
      { id: 's14q6', type: 'reflection', question: 'What boundaries did you have growing up? Were they healthy or unhealthy?' },
      { id: 's14q7', type: 'assignment', question: 'Write scripts for 3 boundary-setting conversations you need to have.', hint: 'Use "I" statements and be clear about consequences.' },
      { id: 's14q8', type: 'reflection', question: 'How do you handle it when someone violates your boundaries?' },
      { id: 's14q9', type: 'journaling', question: 'Describe the difference between walls and boundaries. Which do you tend to build?' },
      { id: 's14q10', type: 'reflection', question: 'What boundaries do you need with social media and technology for your recovery?' },
      { id: 's14q11', type: 'assignment', question: 'Create a list of your non-negotiable boundaries - things you will never compromise on in recovery.' },
      { id: 's14q12', type: 'reflection', question: 'How does people-pleasing undermine your boundaries and recovery?' },
      { id: 's14q13', type: 'exercise', question: 'Notice every time you override your own boundaries today. Write about each instance.' },
      { id: 's14q14', type: 'journaling', question: 'Write about a relationship where boundaries are particularly difficult. What makes it hard?' },
      { id: 's14q15', type: 'reflection', question: 'What boundaries do you need to set with yourself regarding your recovery?' },
      { id: 's14q16', type: 'reflection', question: 'How do boundaries actually strengthen relationships rather than weaken them?' },
      { id: 's14q17', type: 'assignment', question: 'Set one new boundary this week. Track how maintaining it affects your well-being.' },
      { id: 's14q18', type: 'reflection', question: 'How can you tell the difference between a healthy boundary and isolation?' },
      { id: 's14q19', type: 'journaling', question: 'Write about what your life looks like when all your boundaries are in place and respected.' },
      { id: 's14q20', type: 'reflection', question: 'What support do you need to maintain your boundaries consistently?' },
    ],
  },
  {
    id: 'sec-15',
    title: 'Shame & Vulnerability',
    description: 'Confront shame and embrace vulnerability as strength',
    unlockMilestoneDays: 60,
    questions: [
      { id: 's15q1', type: 'reflection', question: 'What is your greatest source of shame related to your addiction?' },
      { id: 's15q2', type: 'journaling', question: 'Write about a shameful moment in your addiction. Write it fully, without holding back.' },
      { id: 's15q3', type: 'reflection', question: 'How does shame keep you trapped in the addiction cycle?' },
      { id: 's15q4', type: 'assignment', question: 'Identify 3 shame messages you carry (e.g., "I am not good enough"). Write a truth to counter each one.' },
      { id: 's15q5', type: 'reflection', question: 'Who have you shared your shame with? How did it feel?' },
      { id: 's15q6', type: 'exercise', question: 'Share something vulnerable with a trusted person this week. Write about the experience.' },
      { id: 's15q7', type: 'reflection', question: 'How is vulnerability different from weakness? Why does society confuse them?' },
      { id: 's15q8', type: 'journaling', question: 'Write about a time when being vulnerable led to a positive outcome.' },
      { id: 's15q9', type: 'reflection', question: 'What would change in your life if shame no longer had power over you?' },
      { id: 's15q10', type: 'assignment', question: 'Write a "shame resilience" plan: What will you do when shame hits? Include 5 steps.' },
      { id: 's15q11', type: 'reflection', question: 'How does secrecy feed shame? What secrets are you still keeping?' },
      { id: 's15q12', type: 'journaling', question: 'Write about the connection between shame and isolation. How do they reinforce each other?' },
      { id: 's15q13', type: 'reflection', question: 'What would you say to a friend who shared the same shame you carry?' },
      { id: 's15q14', type: 'exercise', question: 'Practice self-compassion when shame arises today. Place your hand on your heart and say "This is hard, and I am worthy." Report on the experience.' },
      { id: 's15q15', type: 'reflection', question: 'How has your shame evolved since starting recovery?' },
      { id: 's15q16', type: 'assignment', question: 'Write about 3 things you are ashamed of that you have never told anyone. Consider sharing one with a safe person.' },
      { id: 's15q17', type: 'reflection', question: 'What is the relationship between perfectionism and shame in your life?' },
      { id: 's15q18', type: 'journaling', question: 'Imagine shame as a person. What does it look like? What does it say? How can you respond?' },
      { id: 's15q19', type: 'reflection', question: 'How can you practice vulnerability daily in small ways?' },
      { id: 's15q20', type: 'journaling', question: 'Write about a moment of genuine connection that came from being vulnerable.' },
    ],
  },
];
