import { WorkbookSection } from '@/types';

export const WORKBOOK_SECTIONS_1_5: WorkbookSection[] = [
  {
    id: 'sec-1',
    title: 'Understanding Addiction',
    description: 'Explore the roots and nature of your addiction',
    unlockMilestoneDays: 0,
    questions: [
      { id: 's1q1', type: 'reflection', question: 'What does addiction mean to you in your own words?' },
      { id: 's1q2', type: 'journaling', question: 'Describe the first time you used your substance or engaged in your addictive behavior. What were the circumstances?' },
      { id: 's1q3', type: 'reflection', question: 'What emotions were you trying to escape or enhance when your addiction began?' },
      { id: 's1q4', type: 'assignment', question: 'List 5 ways addiction has negatively impacted your life.', hint: 'Consider health, relationships, finances, career, and self-esteem.' },
      { id: 's1q5', type: 'reflection', question: 'How has your addiction changed over time? Has it gotten worse or shifted forms?' },
      { id: 's1q6', type: 'journaling', question: 'Write about a moment when you realized your behavior had become a problem.' },
      { id: 's1q7', type: 'reflection', question: 'What lies has your addiction told you to keep you coming back?' },
      { id: 's1q8', type: 'assignment', question: 'Research and write down 3 facts about how your specific addiction affects the brain.', hint: 'Understanding the science can reduce shame.' },
      { id: 's1q9', type: 'reflection', question: 'Who in your life has been most affected by your addiction? How?' },
      { id: 's1q10', type: 'exercise', question: 'Practice this: Sit quietly for 5 minutes and observe any cravings or urges without acting on them. Write about the experience.' },
      { id: 's1q11', type: 'journaling', question: 'What does your life look like when addiction is in control versus when you are in control?' },
      { id: 's1q12', type: 'reflection', question: 'What are you most afraid of about recovery?' },
      { id: 's1q13', type: 'assignment', question: 'Write a letter to your addiction. Tell it how it has affected you and why you are choosing to let go.' },
      { id: 's1q14', type: 'reflection', question: 'Do you believe addiction is a disease, a choice, or something else? Why?' },
      { id: 's1q15', type: 'journaling', question: 'Describe your typical day when your addiction was at its worst.' },
      { id: 's1q16', type: 'reflection', question: 'What positive things did you believe your addiction gave you? Were they real?' },
      { id: 's1q17', type: 'assignment', question: 'Identify 3 people you trust enough to talk to about your recovery journey.', hint: 'Support is crucial in early recovery.' },
      { id: 's1q18', type: 'reflection', question: 'How does shame play a role in your addiction cycle?' },
      { id: 's1q19', type: 'exercise', question: 'Create a timeline of your addiction from start to now. Mark key events and turning points.' },
      { id: 's1q20', type: 'journaling', question: 'What gives you hope that recovery is possible for you?' },
    ],
  },
  {
    id: 'sec-2',
    title: 'Motivation & Commitment',
    description: 'Strengthen your reasons for recovery',
    unlockMilestoneDays: 0,
    questions: [
      { id: 's2q1', type: 'reflection', question: 'Why do you want to recover? List your top 5 reasons.' },
      { id: 's2q2', type: 'journaling', question: 'Describe the life you want to live in 1 year if you stay on the recovery path.' },
      { id: 's2q3', type: 'assignment', question: 'Write your personal recovery mission statement in 2-3 sentences.', hint: 'This should capture your core motivation.' },
      { id: 's2q4', type: 'reflection', question: 'What will you lose if you do not change? Be brutally honest.' },
      { id: 's2q5', type: 'journaling', question: 'Write about a person who inspires you in recovery or in life. What qualities do they have?' },
      { id: 's2q6', type: 'reflection', question: 'On a scale of 1-10, how committed are you to recovery right now? What would make it a 10?' },
      { id: 's2q7', type: 'assignment', question: 'Create a vision board description: Write about 10 images that represent your ideal sober life.' },
      { id: 's2q8', type: 'reflection', question: 'What excuses do you commonly make to justify using? How can you counter them?' },
      { id: 's2q9', type: 'exercise', question: 'Write your commitment on paper and sign it. Describe how that felt.' },
      { id: 's2q10', type: 'journaling', question: 'What does freedom from addiction look like to you?' },
      { id: 's2q11', type: 'reflection', question: 'Who are you doing this for — yourself, your family, or both? Why?' },
      { id: 's2q12', type: 'assignment', question: 'List 10 things you will be able to do or enjoy more fully in sobriety.' },
      { id: 's2q13', type: 'reflection', question: 'What is the biggest sacrifice you are making for recovery? Is it worth it?' },
      { id: 's2q14', type: 'journaling', question: 'Write about a time when you felt truly proud of yourself. What made that moment special?' },
      { id: 's2q15', type: 'reflection', question: 'How will your daily routine change in recovery? What new habits will you adopt?' },
      { id: 's2q16', type: 'exercise', question: 'Each morning this week, say out loud: "I choose recovery today." Write about how this practice affects you.' },
      { id: 's2q17', type: 'reflection', question: 'What is the cost of one more relapse? Consider all areas of your life.' },
      { id: 's2q18', type: 'assignment', question: 'Write a letter to your future sober self. What do you want to tell them?' },
      { id: 's2q19', type: 'reflection', question: 'What small wins have you already achieved in recovery? Celebrate them.' },
      { id: 's2q20', type: 'journaling', question: 'Describe the moment you decided enough was enough. What triggered that decision?' },
    ],
  },
  {
    id: 'sec-3',
    title: 'Identifying Triggers',
    description: 'Recognize what drives your addictive behavior',
    unlockMilestoneDays: 1,
    questions: [
      { id: 's3q1', type: 'reflection', question: 'What are your top 5 emotional triggers for using or engaging in addictive behavior?' },
      { id: 's3q2', type: 'assignment', question: 'Map out your typical trigger-response chain: Trigger → Thought → Craving → Action. Give 3 examples.' },
      { id: 's3q3', type: 'journaling', question: 'Describe a recent situation where you felt triggered. What happened before, during, and after?' },
      { id: 's3q4', type: 'reflection', question: 'Which people in your life trigger your addictive behavior? Why?' },
      { id: 's3q5', type: 'assignment', question: 'List 5 places or environments that trigger cravings. How can you avoid or manage them?', hint: 'Create a plan for each one.' },
      { id: 's3q6', type: 'reflection', question: 'What time of day are you most vulnerable to cravings? What is happening during that time?' },
      { id: 's3q7', type: 'exercise', question: 'For the next 3 days, keep a trigger journal. Note every time you feel a craving, what triggered it, and how you responded.' },
      { id: 's3q8', type: 'reflection', question: 'How does stress act as a trigger for you? What stresses you the most?' },
      { id: 's3q9', type: 'journaling', question: 'Write about a time you successfully resisted a trigger. What strategies did you use?' },
      { id: 's3q10', type: 'reflection', question: 'Do certain emotions like loneliness, boredom, or anger trigger you more than others? Which ones?' },
      { id: 's3q11', type: 'assignment', question: 'Create a "trigger emergency plan" with 5 actions you can take when triggered.', hint: 'Include calling someone, exercise, breathing, etc.' },
      { id: 's3q12', type: 'reflection', question: 'How does social media or technology trigger your addictive behavior?' },
      { id: 's3q13', type: 'journaling', question: 'Write about the physical sensations you experience when triggered. Where do you feel it in your body?' },
      { id: 's3q14', type: 'reflection', question: 'What role does HALT (Hungry, Angry, Lonely, Tired) play in your triggers?' },
      { id: 's3q15', type: 'exercise', question: 'Practice the 5-4-3-2-1 grounding technique when triggered: 5 things you see, 4 you touch, 3 you hear, 2 you smell, 1 you taste. Write about the experience.' },
      { id: 's3q16', type: 'reflection', question: 'Are there seasonal or calendar-related triggers for you (holidays, anniversaries, etc.)?' },
      { id: 's3q17', type: 'assignment', question: 'Write down 3 healthy replacement behaviors for each of your top 3 triggers.' },
      { id: 's3q18', type: 'reflection', question: 'How can you modify your environment to reduce trigger exposure?' },
      { id: 's3q19', type: 'journaling', question: 'Describe what happens in your mind between the trigger and the decision to use. What thoughts arise?' },
      { id: 's3q20', type: 'reflection', question: 'What have you learned about your triggers that surprised you?' },
    ],
  },
  {
    id: 'sec-4',
    title: 'Coping Strategies',
    description: 'Build your toolkit for handling difficult moments',
    unlockMilestoneDays: 3,
    questions: [
      { id: 's4q1', type: 'reflection', question: 'What coping strategies have you used in the past that actually worked?' },
      { id: 's4q2', type: 'assignment', question: 'List 10 healthy activities you can do instead of using when cravings hit.', hint: 'Include physical, social, creative, and calming activities.' },
      { id: 's4q3', type: 'exercise', question: 'Practice deep breathing: 4 counts in, 7 counts hold, 8 counts out. Do this for 5 minutes and describe how you feel.' },
      { id: 's4q4', type: 'journaling', question: 'Write about a time when a craving passed without you giving in. How long did it last?' },
      { id: 's4q5', type: 'reflection', question: 'How does physical exercise help you cope with cravings? What types of exercise appeal to you?' },
      { id: 's4q6', type: 'assignment', question: 'Create a daily routine that includes at least 3 coping strategies built into your day.' },
      { id: 's4q7', type: 'reflection', question: 'What role does talking to others play in your coping? Who can you call when struggling?' },
      { id: 's4q8', type: 'exercise', question: 'Try progressive muscle relaxation: tense each muscle group for 5 seconds then release. Write about the experience.' },
      { id: 's4q9', type: 'reflection', question: 'How does creative expression (art, music, writing) help you process difficult emotions?' },
      { id: 's4q10', type: 'journaling', question: 'Write about a healthy coping mechanism you have never tried but would like to explore.' },
      { id: 's4q11', type: 'reflection', question: 'What unhealthy coping mechanisms do you need to replace? What will you replace them with?' },
      { id: 's4q12', type: 'assignment', question: 'Create a "coping card" you can carry: Write 5 reminders of why you are sober and 5 things to do instead of using.' },
      { id: 's4q13', type: 'reflection', question: 'How does nature and being outdoors affect your mental state and cravings?' },
      { id: 's4q14', type: 'exercise', question: 'Practice mindful eating at your next meal. Eat slowly, notice textures and flavors. Write about the experience.' },
      { id: 's4q15', type: 'reflection', question: 'What role does sleep play in your ability to cope? How can you improve your sleep habits?' },
      { id: 's4q16', type: 'journaling', question: 'Describe your ideal "crisis toolkit" — everything you need to get through a tough moment.' },
      { id: 's4q17', type: 'reflection', question: 'How can you use humor as a coping strategy without minimizing your struggles?' },
      { id: 's4q18', type: 'assignment', question: 'Schedule one new coping activity for each day this week. At the end, reflect on which ones helped most.' },
      { id: 's4q19', type: 'reflection', question: 'What is the difference between coping and avoiding? When do you cross that line?' },
      { id: 's4q20', type: 'journaling', question: 'Write about your strongest moment in recovery so far. What coping strategies were you using at that time?' },
    ],
  },
  {
    id: 'sec-5',
    title: 'Emotional Awareness',
    description: 'Learn to identify and process your feelings',
    unlockMilestoneDays: 3,
    questions: [
      { id: 's5q1', type: 'reflection', question: 'How comfortable are you with feeling your emotions? Rate yourself 1-10 and explain.' },
      { id: 's5q2', type: 'assignment', question: 'List 20 different emotions you have experienced in the past week. Be as specific as possible.' },
      { id: 's5q3', type: 'journaling', question: 'Write about an emotion you tend to avoid. Why do you avoid it? What happens when you do feel it?' },
      { id: 's5q4', type: 'reflection', question: 'How did you learn to handle emotions growing up? What did your family teach you?' },
      { id: 's5q5', type: 'exercise', question: 'Set a timer for every 2 hours today. Each time it goes off, identify and write down what emotion you are feeling.' },
      { id: 's5q6', type: 'reflection', question: 'Which emotions are hardest for you to sit with? Why?' },
      { id: 's5q7', type: 'journaling', question: 'Write about anger. How do you typically express it? Is it healthy or destructive?' },
      { id: 's5q8', type: 'reflection', question: 'How does sadness manifest in your body? What physical sensations accompany it?' },
      { id: 's5q9', type: 'assignment', question: 'Create an "emotions wheel" for yourself: Write the primary emotion in the center and secondary emotions branching out.' },
      { id: 's5q10', type: 'reflection', question: 'When you feel joy, do you trust it? Or do you wait for something bad to happen?' },
      { id: 's5q11', type: 'journaling', question: 'Describe a time when you numbed an emotion with your addiction. What was the emotion? What would happen if you felt it fully?' },
      { id: 's5q12', type: 'reflection', question: 'How do you differentiate between a feeling and a fact? Give an example.' },
      { id: 's5q13', type: 'exercise', question: 'Practice "emotional labeling": For 24 hours, name every emotion you feel out loud. Write about what you notice.' },
      { id: 's5q14', type: 'reflection', question: 'What role does anxiety play in your daily life? How does it connect to your addiction?' },
      { id: 's5q15', type: 'assignment', question: 'Write a healthy response plan for 5 different emotions (anger, sadness, fear, loneliness, boredom).' },
      { id: 's5q16', type: 'reflection', question: 'How has your emotional range expanded since starting recovery?' },
      { id: 's5q17', type: 'journaling', question: 'Write about gratitude. What are you grateful for today? How does gratitude affect your emotional state?' },
      { id: 's5q18', type: 'reflection', question: 'Do you use emotional eating, shopping, or other substitutes for your primary addiction? How?' },
      { id: 's5q19', type: 'exercise', question: 'Spend 10 minutes journaling stream-of-consciousness about whatever emotions arise. Do not censor yourself.' },
      { id: 's5q20', type: 'journaling', question: 'What emotion are you feeling right now? Describe it in detail without judgment.' },
    ],
  },
];
